config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :roles
  devise_for :users

  scope "/admin" do
    resources :users
  end
  
  resources :articles
  resources :categories

   root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource # invoking ability.rb 

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @category = Category.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id 
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :category_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name,{prompt: "Select Category"}, {class: "form-control"} %>
  </div>

  <div class="field">
    <%= f.label :published_date %><br>
    <%= f.text_field :published_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>

        <% if can? :update, article %> 
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <% end %>

        <% if can? :destroy, article %>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Article.new %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<div class="row">
	<div class="col-md-8">
			<div class="page-header">
				<h2>Add Article</h2>
			</div>
				<%= render 'form' %>
	</div>

	<div class="col-md-4">
	
		<div class="page-header">
			<h2>Add Category</h2>
		</div>
		
		<%= render './categories/form' %>

		<div class="page-header">
				<h2>Categories</h2>
			</div>

		<ul class="list-group">
			<% Category.all.each do |category| %>
		  <li class="list-group-item">
		    <span class="badge"><%= category.articles.size %></span>
		    <%= category.name %>
		  </li>
		  <% end %>
		</ul>

	</div>
</div>





<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<% if can? :update, @article %>
	<%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>

<h2>Previous Comments</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article.comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.article_id %></td>
        <% if can? :update, comment %>
        	<td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <% end %>
        <% if can? :destroy, comment %>
        	<td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% @comment = Comment.new %>

<% if user_signed_in? %>
	<h2>Add Comment </h2>
	<%= render '/comments/form' %>
<% end %>

<%= link_to 'Back', articles_path %>