config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :roles
  devise_for :users

  scope "/admin" do
    resources :users
  end
  
  resources :articles
  resources :categories

   root 'articles#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource # invoking ability.rb 

  #before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to :back, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
        format.js
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end


=begin 
  respond_to do |format| 
  if @category.save
    format.html {redirect_to  }
    format.js
  else 
    render action: "new"
=end 

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<li class="list-group-item">
		    <span class="badge"><%= @category.articles.size %></span>
		    <%= @category.name %>
</li>

app/views/categories/_option.html.erb
<option value="<%= @category.id %>" selected="selected"><%= @category.name %></option>

app/views/categories/create.js.erb
$('#new_category')[0].reset();
$('#article_category_id').append("<%= escape_javascript(render 'option')%>");

$('.list-group').append("<%= escape_javascript(render 'list')%>");

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to category_path(category.id) do %>
            <i class="glyphicon glyphicon-eye-open
"></i> 
          <% end %>

        </td>
        <td>
          <%= link_to edit_category_path(category.id) do %>
            <i class="glyphicon glyphicon-pencil
"></i> 
          <% end %>
        </td>
        <td>
        <% if can? :destroy, category %> 
          <%= link_to category_path(category.id), method: :delete, data: {confirm: "Are you sure"} do %>
            <i class="glyphicon glyphicon-trash"></i> 
          <% end %>
        <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Category.new %>
  <%= link_to new_category_path, class: "btn btn-primary" do %>
    <i class="glyphicon glyphicon-plus"></i> Add Category
  <% end %>
<% end %> 


<%#= link_to "Add Category", new_category_path, class: "btn btn-primary glyphicon glyphicon-plus" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<% ajax_form = false %>
<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>